### PR TITLE
Fix double trailing parenthesis after `noexcept(cond)`

### PR DESCRIPTION
**Pull request by Lastique**
This removes the redundant trailing parenthesis after `noexcept(cond)` function qualifiers.

Fixes https://github.com/boostorg/boostbook/issues/20.

Also clears executable permission from an XSLT file.

### CODE REVIEW

**Comment by Lastique** [comment]
@glenfe I'm not sure who is maintaining BoostBook these days, but since you merged PRs here, could to take a look, please? It would be nice to have this fixed in the next release.

**Comment by glenfe** [comment]
@Lastique Thanks for fixing issues like this. After the develop doc build completes, is the a library's docs we can compare between develop and master to see the effect of the noexcept change?

**Comment by Lastique** [comment]
I referenced [Boost.Intrusive](https://www.boost.org/doc/libs/1_81_0/doc/html/boost/intrusive/hashdata_internal.html#idm32877-bb) docs as an example in #20.

**Comment by Lastique** [comment]
And thanks for merging, BTW. Please, remember to merge to master as well.

**Pull request merged**
